### PR TITLE
using two count steps to reduce total work done to calculate next gen.

### PR DESCRIPTION
**Pull request by dc25**
This speeds up the program.  By about a factor of two I think but I didn't measure it.

### CODE REVIEW

**Comment by fbonetti** [comment]
Unless I'm misreading the code, this code is faster because it examines only 4 neighbors, instead of 8. Conway's Game of Life requires that we look at the diagonal neighbors as well.

From wikipedia:

> Every cell interacts with its eight neighbours, which are the cells that are horizontally, vertically, or diagonally adjacent.

**Comment by dc25** [comment]
It examines all 8 neighbors.  This happens in two steps.  First sum left/center/right neighbors for all cells, then sum top/center/bottom values using previous values as input.  

So, for example if you start with this pattern:

XXO
OXO
XXX

after the first step, you get

?2?
?1?
?3?

and after the second step, you get

???
?6?
???

The question marks indicate values that I can't calculate in this example because I only am showing 9 cells and the cells on the edge are influenced by their own neighbors which I'm not showing here ( but would be known in the actual simulation ).

The result is 6 which accounts for the center cell's 5 neighbors plus the center cell itself.  This technique counts the cell itself ( if it is alive ) which means that the rules have to be changed accordingly - mostly just bumped up by one.  

Here's a link to a working version : http://dc25.github.io/elm-game-of-life/

If the diagonal neighbors were not being accounted for then the behavior would be noticeably different.

**Comment by fbonetti** [comment]
Hmm... I'll have to examine this more because I don't understand how this checks all 8 neighbors when `Matrix.get` only gets called 4 times. I also don't understand why there's a `partialSum` and a `fullSum` function - it seems like it's inefficient to process the `Grid` twice.

Also, all cells are supposed to evolve simultaneously. Are you sure that processing the grid with `partialSum` and `fullSum` doesn't bias the outcome?

Since I'm having trouble understanding the code, I'd like to run them side by side and visually compare the difference.

**Comment by dc25** [comment]
Here's an example that might shed some light on what's going on:

Suppose you have this pattern ...

XOOX
X**X**XO          <---- highlighted X has 5 neighbors (counting itself as a neighbor)
O**O**XX         <----  highlighted O has 6 neighbors
X**O**XX         <----- highlighted O has 4 neighbors
XOOO

The first step is to count left right and self neighbors horizontally which results in these numbers....

?11?
?32?
?**1**2?  <--- watch where the 1 value goes
?22?
?10?

Again, the question marks indicate that there's not enough information here to compute a value..

The second step is to sum upper, lower, and center values vertically which results in these numbers...

????
?**5**5?   <---- note that 5 ==  1+3+**1**
?**6**7?   <---- note that 6 == 3+**1**+2 
?**4**4?   <---- note that 4 == **1**+2+1
????

The resulting output is the neighbor counts for the original cells ( if you count a cell as a neighbor of itself ).

The thing to notice in these calculations is that the "1" that is highlighted in step 1 is used three times in step 2 but was only calculated once ( in step 1).  This reuse is where the better performance comes from.

You can think of it like this : each cell requires access to 3 horizontal sets of 3 cells and then 1 vertical set of 3 cells.  This sounds like 12 accesses but each of those 3 horizontal sets is **shared** between the computations for 3 different cells.  So the cost for one cell is just 1 horizontal set and 1 vertical set of accesses - a total of 6 accesses.  The original code was accessing each of the neighbors (8 accesses) so it took longer.  In addition, the original code was doing some list manipulation which might be expensive.

I updated the published version to do both computations, display them both, and display the difference between the two as well.   I made the width and height smaller so that it would fit on a screen without needing to scroll.

The code is in the same repository on a branch called compare : https://github.com/dc25/elm-game-of-life/blob/compare/Main.elm

The demo link is the same as before:  http://dc25.github.io/elm-game-of-life/

As you can see, there's no difference between the two.

**Pull request closed without merging**
